version: 0.0
os: linux
files:
  - source: ./order-service.war
    destination: /opt/apache-tomcat/webapps/
hooks:
  BeforeInstall:
      - location: ./before_install.sh
  AfterInstall:
      - location: ./after_install.sh
